site_name: ModelSEEDagent Documentation
site_description: AI-Powered Metabolic Modeling Platform
site_author: ModelSEED Team
repo_url: https://github.com/ModelSEED/ModelSEEDagent
repo_name: ModelSEED/ModelSEEDagent

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

nav:
  - Home: index.md
  
  - User Guide:
    - Getting Started: user/README.md
    - User Guide: user/INTERACTIVE_GUIDE.md
  
  - Technical Reference:
    - Architecture: ARCHITECTURE.md
    - Tool Reference: TOOL_REFERENCE.md
    - Debug Configuration: debug.md
    - Troubleshooting: troubleshooting.md
  
  - API Documentation:
    - Overview: api/overview.md
  
  - Operations:
    - Installation: installation.md