site_name: ModelSEEDagent Documentation
site_description: AI-Powered Metabolic Modeling Platform
site_author: ModelSEED Team
repo_url: https://github.com/ModelSEED/ModelSEEDagent
repo_name: ModelSEED/ModelSEEDagent

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mtml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md

  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start (CLI): getting-started/quickstart-cli.md
    - Interactive Guide: getting-started/interactive-guide.md

  - User Guide:
    - CLI Reference: user-guide/cli-reference.md
    - Tool Catalogue: user-guide/tool-catalogue.md
    - FAQ: user-guide/faq.md

  - Technical Reference:
    - Architecture: ARCHITECTURE.md
    - Tool Reference (catalogue): user-guide/tool-catalogue.md
    - Tool Reference Pages: tool-reference/index.md
    - Tool Testing Status: TOOL_TESTING_STATUS.md
    - Debug Configuration: debug.md
    - Troubleshooting: troubleshooting.md

  - API Documentation:
    - Overview: api/overview.md
    - Tool Implementation: api/tools.md

  - Developer:
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Style Guide: developer/style-guide.md
    - Roadmap: development/DEVELOPMENT_ROADMAP.md

  - Operations:
    - Deployment: operations/deployment.md
    - Monitoring: operations/monitoring.md
    - Documentation Automation: operations/documentation-automation.md
