llm:
  llm_backend: "argo"  # Change to "argo" or "local" to switch
  safety_settings:
    enabled: false
    max_api_calls: 100
    max_tokens: 50000
argo:
  user: "your_username"
  system_content: "You are an AI assistant specialized in metabolic modeling."
  models:
    gpt35:
      api_base: "YOUR_API_BASE_URL"
      model_name: "gpt35"
    gpt4:
      api_base: "YOUR_API_BASE_URL"
      model_name: "gpt4"
    gpt4turbo:
      api_base: "YOUR_API_BASE_URL"
      model_name: "gpt4turbo"
    gpt4o:
      api_base: "YOUR_API_BASE_URL"
      model_name: "gpt4o"      
  default_model: "gpt4o"
local:
  model_name: "llama-3.2-3b"
  model_path: "PATH_TO_YOUR_MODEL"
  system_content: "You are an AI assistant specialized in metabolic modeling."
  device: "mps"
  max_tokens: 500
  temperature: 0.7
  models:
    llama-3.1-8b:
      model_name: "llama-3.1-8b"
      model_path: "PATH_TO_YOUR_MODEL"
      device: "mps"
      max_tokens: 500
      temperature: 0.7
    llama-3.2-3b:
      model_name: "llama-3.2-3b"
      model_path: "PATH_TO_YOUR_MODEL"
      device: "mps"
      max_tokens: 500
      temperature: 0.7
tools:
  configs:
    fba_config:
      default_objective: "biomass_reaction"
      solver: "glpk"
      tolerance: 1e-6
agent:
  max_iterations: 5
  verbose: false
  handle_parsing_errors: true
  default_type: "metabolic"