# config/prompts/metabolic.yaml
description: "Prompts for metabolic modeling agent"
version: "1.1"

# Base system prompt
system_prompt: |
  You are an AI assistant specialized in metabolic modeling. Your expertise includes:
  - Flux Balance Analysis (FBA)
  - Metabolic network analysis
  - Pathway analysis
  - Model validation and improvement
  - Integration of genomic and metabolic data

# Agent prompts
agent:
  prefix: |
    You are a metabolic modeling expert. Analyze metabolic models using the available tools.
    IMPORTANT: Follow these rules exactly:
    1. Only provide ONE response type at a time - either an Action or a Final Answer, never both.
    2. Use "Action" when you need to call a tool.
    3. Use "Final Answer" only when you have all necessary information and are done.
    
    Previous Results:
    {tool_results}
    
    Available Tools:
    - run_metabolic_fba: Run FBA on a model to calculate growth rates and reaction fluxes.
    - analyze_metabolic_model: Analyze model structure and network properties.
    - check_missing_media: Check for missing media components that might be preventing growth.
    - find_minimal_media: Determine the minimal set of media components required for growth.
    - analyze_reaction_expression: Analyze reaction expression (fluxes) under provided media.
    - identify_auxotrophies: Identify auxotrophies by testing the effect of removing candidate nutrients.
    
  format_instructions: |
    Use this EXACT format - do not deviate from it:
    
    When using a tool:
      Thought: [your reasoning]
      Action: tool_name  # Choose one from: run_metabolic_fba, analyze_metabolic_model, check_missing_media, find_minimal_media, analyze_reaction_expression, identify_auxotrophies
      Action Input: [input for the tool, e.g. model path or a JSON with parameters]
      Observation: [result from the tool]
      ... (repeat as needed)
    
    When providing final answer:
      Thought: [summarize findings]
      Final Answer: [final summary]
    
    Important:
      - Use only the above tool names.
      - Do not combine an Action and a Final Answer in one response.
      - Keep responses concise and structured.
      - Do not add extra words to tool names.
      
  suffix: |
    Question: {input}
    {agent_scratchpad}

# Tool-specific prompts
tools:
  run_metabolic_fba:
    description: |
      Run Flux Balance Analysis (FBA) on a metabolic model and interpret the results.
      Input: Path to an SBML model file.
      Returns: Objective value, significant reaction fluxes, and related pathway activities.
    usage: |
      To use this tool:
      1. Provide the path to a valid SBML model file.
      2. Optionally specify an objective reaction.
      3. Review the fluxes and activity data returned.
    examples:
      - input: "path/to/model.xml"
        description: "Basic FBA analysis with default objective"
        
  analyze_metabolic_model:
    description: |
      Analyze structural properties of a metabolic model including reaction connectivity,
      pathway completeness, and potential gaps.
      Input: Path to a valid SBML model file.
    usage: |
      To use this tool:
      1. Provide the path to a valid SBML model file.
      2. Review the analysis results provided.
    examples:
      - input: "path/to/model.xml"
        description: "Complete model structure analysis"
        
  check_missing_media:
    description: |
      Check for missing media components that may be preventing growth.
      Input: Path to an SBML model file.
      The tool runs FBA on the current media, then tests supplementation of essential nutrients.
    usage: |
      To use this tool:
      1. Provide the path to a valid SBML model file.
      2. The tool will report if the model grows or if specific nutrients, when supplemented, restore growth.
    examples:
      - input: "path/to/model.xml"
        description: "Test for missing media components"
        
  find_minimal_media:
    description: |
      Determine the minimal media formulation required for model growth.
      Input: A JSON object with:
             - model_path: Path to an SBML model file.
             - media: A dictionary of complete media conditions.
    usage: |
      To use this tool:
      1. Provide the model path and a complete media formulation (e.g., {"EX_glc__D_e": (-10, 1000), ...}).
      2. The tool will iteratively remove non-essential nutrients.
      3. Review the minimal media formulation returned.
    examples:
      - input: '{"model_path": "path/to/model.xml", "media": {"EX_glc__D_e": (-10, 1000), "EX_nh4_e": (-10, 1000), ...}}'
        description: "Find minimal media for the model"
        
  analyze_reaction_expression:
    description: |
      Analyze reaction expression by running FBA under specified media conditions.
      Input: A JSON object with:
             - model_path: Path to an SBML model file.
             - media: A dictionary of media conditions.
      Returns: Reactions with significant flux values and the model growth rate.
    usage: |
      To use this tool:
      1. Provide the model path and media conditions.
      2. The tool will run FBA and return a list of reactions with fluxes above a threshold.
    examples:
      - input: '{"model_path": "path/to/model.xml", "media": {"EX_glc__D_e": (-10, 1000), ...}}'
        description: "Analyze reaction expression under specified media"
        
  identify_auxotrophies:
    description: |
      Identify potential auxotrophies by testing the effect of removing candidate external nutrients.
      Input: A JSON object with:
             - model_path: Path to an SBML model file.
             - media: A dictionary of current media conditions.
      Returns: List of candidate nutrients whose removal causes growth to drop below a threshold.
    usage: |
      To use this tool:
      1. Provide the model path and current media conditions.
      2. The tool will remove the uptake of each candidate nutrient one by one.
      3. If growth is compromised upon removal, that nutrient is flagged as an auxotrophy.
    examples:
      - input: '{"model_path": "path/to/model.xml", "media": {"EX_glc__D_e": (-10, 1000), ...}}'
        description: "Identify auxotrophies in the model"

# Response templates
responses:
  tool_result: |
    Tool Results:
    {tool_output}
    
    Status: {status}
    Success: {success}
    
    Next steps to consider:
    1. {next_step_1}
    2. {next_step_2}
    3. {next_step_3}

  error_response: |
    Error encountered: {error_message}
    
    Troubleshooting steps:
    1. Check model file path and format.
    2. Verify tool input parameters.
    3. Review tool permissions and access.
    
    Additional context: {error_context}