name: Docs Autogen

on:
  push:
    branches: [dev]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install minimal dependencies only
        run: |
          python -m pip install --upgrade pip
          # Install only the bare minimum needed for the scripts
          pip install typer click pydantic typing-extensions pathlib
          # Add the src directory to Python path instead of installing the full package
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
      - name: Run doc generators
        continue-on-error: true
        run: |
          # CLI reference generation (will skip and use manual version)
          python scripts/generate_cli_reference.py || echo "CLI reference generation skipped/failed"
          # Tool pages generation (may fail without full package, but that's OK)
          python scripts/generate_tool_pages.py || echo "Tool pages generation failed - using existing pages"
      - name: Commit changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name 'docs-bot'
            git config --global user.email 'bot@example.com'
            git add docs/user-guide/cli-reference.md docs/tool-reference scripts/*.py mkdocs.yml
            git commit -m '[autogen] Update CLI and tool reference docs'
            git push
          else
            echo 'No doc changes to commit.'
          fi
